# Generated by Django 5.2.7 on 2025-10-21 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Description du ressenti')),
                ('emotion', models.CharField(blank=True, choices=[('joyeux', 'Joyeux'), ('calme', 'Calme'), ('stresse', 'Stressé'), ('triste', 'Triste'), ('fatigue', 'Fatigué'), ('colere', 'En colère'), ('anxieux', 'Anxieux'), ('neutre', 'Neutre')], max_length=30, null=True)),
                ('intensity', models.PositiveSmallIntegerField(blank=True, help_text='1 à 10', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
