# Generated by Django 5.2.7 on 2025-10-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_moodentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='mood_score',
            field=models.FloatField(blank=True, help_text='Score calculé automatiquement', null=True),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='JournalEntry',
        ),
    ]
