# Generated by Django 5.2.7 on 2025-10-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_moodentry_mood_score_moodentry_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='sentiment_score',
            field=models.FloatField(blank=True, help_text='Analyse sentiment du texte', null=True),
        ),
    ]
