# Generated by Django 5.2.7 on 2025-10-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_moodentry_sentiment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='objectives',
            field=models.TextField(blank=True, help_text="Objectifs suggérés par l'IA"),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='recommendations',
            field=models.TextField(blank=True, help_text="Recommandations pour améliorer l'humeur"),
        ),
    ]
