# Generated by Django 5.2.7 on 2025-10-24 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('sleep_duration', models.FloatField()),
                ('sleep_quality', models.IntegerField()),
                ('steps_daily', models.IntegerField()),
                ('heart_rate_resting', models.IntegerField()),
                ('blood_pressure_systolic', models.IntegerField()),
                ('stress_level', models.IntegerField()),
                ('bmi', models.FloatField()),
                ('health_score', models.FloatField()),
                ('health_category', models.CharField(max_length=20)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('predicted_anomaly', models.BooleanField(default=False)),
                ('anomaly_confidence', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(default='Low', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Donnée de Santé',
                'verbose_name_plural': 'Données de Santé',
                'db_table': 'health_data',
            },
        ),
        migrations.CreateModel(
            name='HealthAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critique'), ('high', 'Élevé'), ('medium', 'Moyen'), ('positive', 'Positif')], max_length=10)),
                ('category', models.CharField(choices=[('sleep', 'Sommeil'), ('cardiac', 'Cardiaque'), ('activity', 'Activité'), ('lifestyle', 'Mode de vie'), ('overall', 'Global')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='detection.healthdata')),
            ],
            options={
                'verbose_name': 'Alerte Santé',
                'verbose_name_plural': 'Alertes Santé',
                'db_table': 'health_alerts',
            },
        ),
    ]
