services:
  # Web Service - Django Application
  - type: web
    name: carnet-sante-django
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    # Use fewer workers to avoid memory pressure on free instances
    startCommand: "gunicorn projetPython.wsgi:application --workers=${WEB_CONCURRENCY:-2} --timeout 120 --keep-alive 5"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: carnet-sante-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: projetPython.settings
      - key: DEBUG
        value: "False"           # values are strings in envVars
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: WEB_CONCURRENCY
        value: "2"

databases:
  - name: carnet-sante-db
    plan: free
    databaseName: carnet_sante
    user: carnet_sante_user
