# Generated by Django 5.2.6 on 2025-10-26 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(choices=[('brain', 'Brain Tumor MRI'), ('cxr', 'Chest X-Ray')], max_length=10)),
                ('predicted_class', models.CharField(max_length=100)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('probabilities', models.JSONField(blank=True, default=dict)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='diagnostics/%Y/%m/%d/')),
                ('summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
