# Generated by Django 5.2.7 on 2025-10-23 22:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0002_alter_dailymetrics_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='acted_upon',
            field=models.BooleanField(default=False, help_text='User indicated they acted on this'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='experiment_group',
            field=models.CharField(blank=True, help_text='A/B test group identifier', max_length=50),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='feedback_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='helpful',
            field=models.BooleanField(blank=True, help_text='User feedback: was this helpful?', null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='model_version',
            field=models.CharField(blank=True, help_text='Version of model that generated this', max_length=50),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='viewed',
            field=models.BooleanField(default=False, help_text='User viewed this recommendation'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', 'created_at'], name='reco_recomm_user_id_bbdb6d_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['source', 'created_at'], name='reco_recomm_source_07113e_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['helpful'], name='reco_recomm_helpful_3aad8e_idx'),
        ),
    ]
