# Generated by Django 5.2.7 on 2025-10-23 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0003_recommendation_acted_upon_and_more'),
    ]

    operations = [
    ]
