# Generated by Django 5.2.7 on 2025-10-25 02:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0004_auto_20251023_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('sedentary', "Sédentaire (peu ou pas d'exercice)"), ('light', 'Légèrement actif (1-3 jours/semaine)'), ('moderate', 'Modérément actif (3-5 jours/semaine)'), ('very_active', 'Très actif (6-7 jours/semaine)'), ('extra_active', 'Extrêmement actif (2x par jour)')], help_text="Niveau d'activité physique habituel", max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='health_goals',
            field=models.CharField(blank=True, choices=[('weight_loss', 'Perte de poids'), ('muscle_gain', 'Prise de masse musculaire'), ('fitness', 'Amélioration de la forme physique'), ('health', 'Santé générale'), ('sleep', 'Amélioration du sommeil'), ('stress', 'Réduction du stress')], help_text='Objectif de santé principal', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Conditions médicales connues (optionnel, pour information uniquement)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Préférences utilisateur (notifications, types de conseils, etc.)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
